version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    restart: unless-stopped
    volumes:
      - ./elasticsearch-storage:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.12.1
    restart: unless-stopped
    volumes:
      - ./config-logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 10514:10514
      - 8080:8080
    links:
      - elasticsearch:elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.12.1
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch