{
 "title": "ssl-orchestrator",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Host", "query": "stats.gauges.f5telemetry.*" }
  ]
 },
 "panels": [
  {
   "title": "Throughput Averages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time({job=\"syslog\", host_modified=\"$Host\"} | unwrap client_bytes_in | __error__ = \"\" [30m]) by (ts) /1000",
     "legendFormat": "Client Bytes In"
    },
    {
     "expr": "avg_over_time({job=\"syslog\", host_modified=\"$Host\"} | unwrap client_bytes_out | __error__ = \"\" [30m]) by (ts) /1000",
     "legendFormat": "Client Bytes Out"
    },
    {
     "expr": "avg_over_time({job=\"syslog\", host_modified=\"$Host\"} | unwrap server_bytes_in | __error__ = \"\" [30m]) by (ts) /1000",
     "legendFormat": "Server Bytes in"
    },
    {
     "expr": "avg_over_time({job=\"syslog\", host_modified=\"$Host\"} | unwrap server_bytes_out | __error__ = \"\" [30m]) by (ts) /1000",
     "legendFormat": "Server Bytes Out"
    }
   ]
  },
  {
   "title": "Connections / SSL TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "aliasSub(stats.gauges.f5telemetry.$Host.systemPerf.sys-performance-all-stats-Client_Connections.Current, '.*sys-performance-all-stats-(.*)\\..*', '\\1')"
    },
    {
     "target": "aliasSub(stats.gauges.f5telemetry.$Host.systemPerf.sys-performance-all-stats-SSL_TPS.Current, '.*sys-performance-all-stats-(.*)\\..*', '\\1')"
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "aliasSub(stats.gauges.f5telemetry.$Host.systemPerf.sys-performance-all-stats-Utilization.Current, '.*sys-performance-all-stats-(.*)\\..*', '\\1')"
    },
    {
     "target": "aliasSub(stats.gauges.f5telemetry.$Host.systemPerf.sys-performance-all-stats-TMM_Memory_Used.Current, '.*sys-performance-all-stats-(.*)\\..*', '\\1')"
    },
    {
     "target": "aliasSub(stats.gauges.f5telemetry.$Host.systemPerf.sys-performance-all-stats-Other_Memory_Used.Current, '.*sys-performance-all-stats-(.*)\\..*', '\\1')"
    }
   ]
  },
  {
   "title": "Average Total Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time({job=\"syslog\", host_modified=\"$Host\"} | unwrap latency | __error__ = \"\" [30m]) by (ts)"
    }
   ]
  },
  {
   "title": "Client Ciphers (Version)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"syslog\", host_modified=\"$Host\"}| __error__ = \"\" [$__range])) by (client_cipher_version)"
    }
   ]
  },
  {
   "title": "Client Ciphers (Name)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"syslog\", host_modified=\"$Host\"}| __error__ = \"\" | client_cipher_name != \"NA\" [$__range])) by (client_cipher_name)"
    }
   ]
  },
  {
   "title": "Server Ciphers (Version)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"syslog\", host_modified=\"$Host\"}| __error__ = \"\" [$__range])) by (server_cipher_version)"
    }
   ]
  },
  {
   "title": "Server Ciphers (Name)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"syslog\", host_modified=\"$Host\"}| __error__ = \"\" | server_cipher_name != \"NA\" [$__range])) by (server_cipher_name)"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10, sum(count_over_time({job=\"syslog\", host_modified=\"$Host\"} | __error__ = \"\" [$__range])) by (source_ip))"
    }
   ]
  },
  {
   "title": "Destinations",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 24 },
   "targets": [
    {
     "expr": "sum by (dest_ip,remote_host)(count_over_time({job=\"syslog\", host_modified=\"$Host\"}| __error__ = \"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Decryption Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"syslog\", host_modified=\"$Host\"} | __error__ = \"\" [$__range])) by (ssl_action)"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
   "targets": [
    {
     "expr": "sum by (protocol_l7,protocol_l4)(count_over_time({job=\"syslog\", host_modified=\"$Host\"}| __error__ = \"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Summary Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"syslog\", host_modified=\"$Host\"}"
    }
   ]
  }
 ]
}